# theme: jekyll-theme-cayman
remote_theme: hydecorp/hydejack #github/pages-gem poole/hyde pages-themes/leap-day@v0.2.0
title: MENTORING3
description: Creative coding with unity
show_downloads: "true"
plugins:
  - jemoji
